pool:
  vmImage: 'ubuntu-16.04'
variables:
  - name: working-dir
    value: 'poker_web/'
  trigger:
  branches:
    include:
      - master
  paths:
    include: # Include!
      - 'poker_web/*'
steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Templates'
    inputs:
      SourceFolder: deployment
      Contents: '*.json'
      TargetFolder: '$(build.artifactstagingdirectory)/Templates'
    workingDirectory: $(working-dir)
  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install --production'
    workingDirectory: $(working-dir)  
  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
    workingDirectory: $(working-dir)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    workingDirectory: $(working-dir)